### ISSUE TITLE
[Update] Sanction list - Add Steam and Rockstar games store

### ISSUE THREAD

**Issue by mohkazv** [alireza-rezaee/sanctions-against-Iran#2]
https://store.steampowered.com/
https://www.rockstargames.com/
<img width="960" alt="1" src="https://user-images.githubusercontent.com/45150276/89456202-c0dd5700-d778-11ea-81f1-5a03354886ec.png">
<img width="943" alt="2" src="https://user-images.githubusercontent.com/45150276/89456211-c3d84780-d778-11ea-8778-ad2fb7f5b30d.png">

**Comment by alireza-rezaee** [comment]
سلام، ممنون
اضافه شدند.

* بازی [Rockstar](Rockstar) - پیمان: [End-user license agreement](https://www.rockstargames.com/eula) - *همراه با مسدودیت آی‌پی*
* بازی [Steam](https://store.steampowered.com/) - پیمان: [Subscriber Agreement](https://store.steampowered.com/subscriber_agreement/#12) - *همراه با مسدودیت آی‌پی*
